# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jstraub/workspace/research/surfelRender/glsl_lighting

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jstraub/workspace/research/surfelRender/glsl_lighting

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jstraub/workspace/research/surfelRender/glsl_lighting/CMakeFiles /home/jstraub/workspace/research/surfelRender/glsl_lighting/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jstraub/workspace/research/surfelRender/glsl_lighting/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glsl_lighting

# Build rule for target.
glsl_lighting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glsl_lighting
.PHONY : glsl_lighting

# fast build rule for target.
glsl_lighting/fast:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/build
.PHONY : glsl_lighting/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/main.c.s
.PHONY : main.c.s

scene.o: scene.c.o
.PHONY : scene.o

# target to build an object file
scene.c.o:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/scene.c.o
.PHONY : scene.c.o

scene.i: scene.c.i
.PHONY : scene.i

# target to preprocess a source file
scene.c.i:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/scene.c.i
.PHONY : scene.c.i

scene.s: scene.c.s
.PHONY : scene.s

# target to generate assembly for a file
scene.c.s:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/scene.c.s
.PHONY : scene.c.s

shader.o: shader.c.o
.PHONY : shader.o

# target to build an object file
shader.c.o:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/shader.c.o
.PHONY : shader.c.o

shader.i: shader.c.i
.PHONY : shader.i

# target to preprocess a source file
shader.c.i:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/shader.c.i
.PHONY : shader.c.i

shader.s: shader.c.s
.PHONY : shader.s

# target to generate assembly for a file
shader.c.s:
	$(MAKE) -f CMakeFiles/glsl_lighting.dir/build.make CMakeFiles/glsl_lighting.dir/shader.c.s
.PHONY : shader.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... glsl_lighting"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... scene.o"
	@echo "... scene.i"
	@echo "... scene.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

